### ISSUE TITLE
Less than and greater than description doesn't match implementation

### ISSUE THREAD

**Issue by KurAnd10** [FlorianRappl/Mages#104]
**In the description section "Included functions":**

- "Less Than" : x = lt(2, 3) // 1 is shown as "true" in documentation but is evaluating as "false". Same is true for matrix representations

- "Greater than": x = gt(2, 3) // 0 is shown as false in documentation but is evaluating as "true". Same is true for matrix representations

The question now is how should it be!

**Comment by FlorianRappl** [comment]
The implementation is right. Due to currying the first argument is the one usually known on the RHS of the operator, i.e., for `2 < 3` the `lt` function uses `lt(3, 2)` to make it possible to call `lt(3)(2)` or `let lessThanThree = lt(3)` etc.

Same applies to all other functions that represent operators (e.g., `sub(3, 2)` is `2-3`).
