### ISSUE TITLE
No result (NaN) returned when adding double and int defined via scope

### ISSUE THREAD

**Issue by KurAnd10** [FlorianRappl/Mages#106]
var engine = new Engine()
var x0 = 1.0;
var x1 = 1;

 engine.Scope.Add("x0", x0);
 engine.Scope.Add("x1", x1);
  
Assert.AreEqual((x0 + x1), engine.Interpret("x0 + x1")); // engine interpret returns NaN

**Comment by FlorianRappl** [comment]
Hm difficult. Directly writing to the scope is supported, but since the scope is a very low level element things like this may appear. There is no operation Int + x defined in MAGES. You need to have Double + Double or Complex + Complex or a mix of the two (actually a few others such as matrices are defined, too).

So if you use the scope directly as shown you need to be aware of the defined operations in the engine.

The only thing we could do is to forbid using the scope directly. I'm, however, not sure if this is the right approach.

**Comment by KurAnd10** [comment]
Hi Florian!

Thanks for clarification. In this case we will handle it on our side!

All the best,
Kurt
