### ISSUE TITLE
Question about results when expecting complex result types

### ISSUE THREAD

**Issue by KurAnd10** [FlorianRappl/Mages#108]
running following fiddle https://dotnetfiddle.net/Hcwnmj the evaluation of 
- "1" shows unexpected result (0, 0) using "ParseFunction" and "ParseComplex" (even if "f" isn't used)
- "f\*1" and "f\*10.5" shows unexpected  result (0, 0) using "ParseFunction"

I think this is because you calculate with double and do not cast it to complex. Am I right?
At the end it seems without checking your code that "result.Call\<Complex\>(f)" and "result.Call(f).ToComplex()" works different. Is this expected?

**Comment by FlorianRappl** [comment]
> I think this is because you calculate with double and do not cast it to complex. Am I right?

Not sure what I did here ;) - I did not write that fiddle. All the calculations are inside MAGES - so if you get a result out, make sure to cast it to the right type (this is .NET specific and nothing MAGES can do for you - we could, of course, throw an exception here, but I don't think that is useful).

> At the end it seems without checking your code that "result.Call<Complex>(f)" and "result.Call(f).ToComplex()" works different. Is this expected?

Yes. `ToComplex` is essentially trying to cast it using MAGES evaluation system. On the other hand, just specifying the generic means "make a .NET as cast". These are two different things.

**Comment by chrfin** [comment]
I'm @KurAnd10 colleague and the create of the fiddle he posted.

I am a "first time MAGES user" and was VERY puzzled by the results of these calculations as I expected the same results from all three variants. IMHO they are mathematically identical and thus should deliver the same result.

\=> I think they either should deliver the same (preferred solution) or at least throw an exception. Otherwise, it could cause awfully hard to find bugs, because you get (correct) results sometimes and sometimes not.

The first variant (`ParseFunction`) may could be avoided by changing the required parameter from `object[]` to `T[]`?

**Comment by FlorianRappl** [comment]
> => I think they either should deliver the same (preferred solution) or at least throw an exception. Otherwise, it could cause awfully hard to find bugs, because you get (correct) results sometimes and sometimes not.

No. Just because you cast results of type double to complex we should throw an exception? This is up to *you*, i.e., the user. MAGES does not care how you use the results. MAGES provides the internal language and runtime. The API layer is up to you.

> IMHO they are mathematically identical and thus should deliver the same result.

That has nothing to do with the observed behavior, which is exclusively about .NET casting behavior.

**Comment by chrfin** [comment]
> No. Just because you cast results of type double to complex we should throw an exception? 

I need to disagree with you here. _I_ do not cast the result - I call MAGES via `Call<T>` and expect a result of type `T`. I just _know_ now because of your explanation that MAGES does an `as`\-cast in that case - there is no way for me to "see that" just from code.

All I am trying to say is that there should be a way for a "stupid user" (like me) to see that when using the method. Throwing an exception (or use a direct cast and let the framework throw the exception) would be one way of doing this. Maybe adding that information to the IntelliSense-comments another. At the moment the method has the same comment as the non-generic method - you could add something like " and safe-cast to T or returns default(T).", so the user knows what's happening if he reads the comment during typing.  
I checked your code and saw you mention this in the "return" comment, but at least Visual Studio and LINQPad do not show you that piece of information in the tooltip.  
In general, I stand by my opinion: If I use `Call<T>` I tell MAGES the result will be `T` and if this is not the case it's best to throw (at least for non-null results in case of a nullable-T). If I'm "not sure" or "don't care" what type the return value will be I can/should use the non-generic overload (and e.g. `ToComplex()`).

**Comment by FlorianRappl** [comment]
> I do not cast the result - I call MAGES via Call<T> and expect a result of type T. I just know now because of your explanation that MAGES does an as-cast in that case - there is no way for me to "see that" just from code.

You get a result of type `T`, but again, if `T` is not compatible with whatever type was in there beforehand you get the given result.

I agree that there is no way of "seeing" that, but this is what documentation is good for. There are more places (in MAGES and any other library / software) where you don't exactly "see" what's going on. That's a case for documentation.

You can keep your opinion. It's fine. Let's agree to disagree. The behavior will not change as its also more of a convenience than a hot path. It's a low level API and users of this API are expected to know what they do (which is the usual case for low level APIs).

**Comment by FlorianRappl** [comment]
Added `CallForced` and improved documentation.
