### ISSUE TITLE
Accessing Object Properties

### ISSUE THREAD

**Issue by TomasaMuller** [FlorianRappl/Mages#114]
Hello, 
If I have a object
for eg.

`TextBox tb = new TextBox();`

and the "tb" instance has a "Name" property
which I set to 
`tb.Name = "tb1;`

now I set the object into the expression engine
```
ExprEngine = new Engine();
ExprEngine.Scope.Add("tb", tb);

```
Now I want to access the text property of the object
what do I do to access it 

I tried doing
`
var result = ExprEngine.Interpret("tb.Name");`

But it doesn't work that way.

**Comment by FlorianRappl** [comment]
Have you tried `tb.name` instead? Usually, the .NET methods are converted to match the convention used within Mages.

**Comment by TomasaMuller** [comment]
Hello,

I tried doing

`var result = ExprEngine.Interpret("tb.name");`

But `result `is `null`

**Comment by FlorianRappl** [comment]
The problem is that you interact directly with the `Scope`, i.e., you place `tb` directly in there. This way, the given object is taken as-is, i.e., it will not be wrapped and therefore while `tb` is accessible, it does not expose any properties.

If you provide it instead, e.g., via `SetConstant` then the object will be wrapped accordingly - this way, the properties are accessible.

Compare:

```cs
void Main()
{
	var tb = new TextBox();
	var engine = new Engine();
	engine.Scope.Add("tb1", tb);
	engine.SetConstant("tb2", tb);
	engine.Interpret("tb1.name").Dump();
	engine.Interpret("tb2.name").Dump();
}

public class TextBox
{
	public string Name => "foo";
}
```

Outcome:

```
null
foo
```

where the first result is from the `tb1` (directly added to `Scope`) and the second result is from `tb2` (added via `SetConstant`).

Hope that helps!

**Comment by TomasaMuller** [comment]
Hello,

Thanks! that worked out.
I tried some more jugglery 
For eg.

```
            TextBox tb = new TextBox();
            tb.Name = "tb_1";
            ExprEngine.SetConstant("tb2", tb);
            var result = ExprEngine.Interpret("tb2.name.length");
```
The expected answer is `4` but result is `null`

**Comment by FlorianRappl** [comment]
`name` is a string and a string is a native Mages type - not proxying here.
