### ISSUE TITLE
Mechanism to raise error incase method call fails.

### ISSUE THREAD

**Issue by TomasaMuller** [FlorianRappl/Mages#121]
Hi

I generally register my own classes into Mages using

```Engine.SetStatic(typeof(SomeClass)).WithDefaultName();```

and then call the static methods inside the class using

```Engine.Interpret("SomeClass.someFunc(arg1, arg2)");```

using proper pascal casing as given in documentation.

However there are times when this call fails, due to parameter mismatch or mainly due to parameter type mismatch, during these times I do not get any exception. The call fails silently.

Is there any mechanism in Mages to raise an exception in case the method call fails.

**Comment by FlorianRappl** [comment]
I think that's a good point; right now there is no error handler. That the calls fail silently is actually by design, but there should be a way to hook up an error handler to the engine / then it could actually be decided how to solve the situation (which also could result in a different output).

**Comment by FlorianRappl** [comment]
Mages now has events that are emitted, e.g., in case of an uncaught error.

However, in the case above there is no error. Mages is also not silent. Functions that are proxied but have a parameter mismatch are treated as-if they have just returned `null`. This is by design and won't be changed. What you can always do is to insert a generic function (i.e., taking any parameters) and emit an error or warning there.
