### ISSUE TITLE
Pattern matching

### ISSUE THREAD

**Issue by FlorianRappl** [FlorianRappl/Mages#58]
Right now MAGES has no `switch`-`case`-like structure for a reason. Instead of providing an ordinary and limited construct I would like to introduce a pattern matching construct. Right now the syntax is still to be determined (any suggestions?).

One could think of (just to throw out something for discussion):

```C
match(X) {
  equals(5) {
  }
  is("String") {
  }
  any {
  }
}
```

Here the construct would start with the keyword `match`, which expects an expression. The result of the expression (called *condition*) is then used in all blocks defined in the next statement block. This a special kind of statement block, a matching block. It consists of statements (called matching statements) that always go in the *expression* *statement-block* form. The expression has to evaluate to a function. The result of invoking the function with the condition is converted to a boolean, which triggers the evaluation of the statement block if true.

The matching block is a breakable construct, i.e., `break` would cancel the search, `continue` would continue to evaluate the condition at the next matching statement.

**Comment by DaisyDave** [comment]
I am just thinking of giving Mages a try and was reading though the current the issues, as you do. I like your idea here, and have couple of questions. I thought I would voice them from the outside, rather than keeping quiet.

1. Your example (I know its just something you threw out there) doesn't include either `break` or `continue` what would you see the default action being at the end of each section? Having worked in C++ in the dim and distant past, I would expect all 3 patterns to be matched even when the first 2 return `true` because the `break` keyword is not present.

1.  Do you see `break` and `continue` working inside each pattern section or just at the end of each section? I created an example to highlight this but realised that what I'm really asking is: would you allow nested `match` statements and what scope do the `break` and `continue` statements have (mainly in the final section of the inner `match`)? An exmple is the outer section would check the type for a numeric variable, then in sub tests would evaluate the range of the number, or am I thinking too C# `select .. case` at this point?

1. Finally do you see the `any` section being optional? Depending on the outcome of my first question this could have a big impact on how easy it is for the user to control flow through the statement and how easy it would be to get unexpected results.

My questions are based on my possible use for this, which would be providing simple scripting for end users in our application. We current;ly use IronPython which scares users because it is a 'programming language'. I suspect some users would be happier with and Excel style `if(<condition>, <true action>, <false action>)`

**Comment by FlorianRappl** [comment]
Hi @DaisyDave - thanks for your input and taking part of the discussion. I try to answer each point separately first, then I try to make a summary to show you my current understanding of the bigger picture of this feature.

1. The default action is to continue with the next section (i.e., fall through for switch-case like scenarios). Why is there a `continue` then? Because one may want to interrupt the current section, but still continue on the next. `break` also interrupts the current section, however, additionally stops the search at all. Hence I see three scenarios (see below). So "Yes", in the example (where I did not specify any body) multiple sections may be executed.
2. Inside each section, i.e., within match only sections are defined via a grammar (such as in the example above). Within a section actual code involving `break` and `continue` is written. I also allow nested `match` statements. Of course, similar to nested loops the inner loop is always taken for a `break` or `continue` statement.
3. `any` is optional. The idea is that only predicates are used as "keys", i.e., functions that fulfill `x -> bool`. `any` is used to determine that something is there. The simplest one I can imagine is `always = (x) => true`, i.e., now one would write `always` instead of `any` (`any(false)` for instance is `false`, likewise `any([])`). I only used `any` in the example to have a minimalistic logic and show that the only requirement is a predicate.

The three scenarios are:

- Stop current section at current point in time and continue on next (`continue`)
- Stop current section at current point and do not continue at all (`break`)
- Do nothing and continue on next (nothing)

So generally the idea is that functions are being used implicitly. Instead of writing `is("String", X)` one is reduced to `is("String")` as currying is already available on a language level. I thought that this kind of pattern matching makes use of some Mages features already and is a good substitute / similar to ordinary switch-case scenarios if wanted.

What's your opinion?
