### ISSUE TITLE
Wipe Engine Context

### ISSUE THREAD

**Issue by wootencl** [FlorianRappl/Mages#83]
Question: Are engine instantiation and plugin adding costly (in regards to performance) operations? If not, then my question/thoughts may be a non issue. 

If those _are_ costly operations, then I would say it may be a good idea to introduce a function to wipe engine context to a fresh state. 

Reasoning/use case behind this: I instantiate the engine and integrate my custom plugins. I then execute the following to add to the engine's current context and interpret a function:

```
engine.Scope["var1"] = 5.0;
engine.Scope["var2"] = 10.0;
engine.Interpret("test_func = (x, y) => x * y");
engine.Interpret("test_func(var1, var2)")
```
I'm less worried about naming collisions as I think MAGES handles variable parsing well. Mostly thinking if I do this several hundred times with different names (i.e. - `var3`, `var4`, `test_func2`) my engine context will become quite polluted/bloated.

Proposed solution would be to offer the ability to wipe an already instantiated engine's context. As mentioned above, if instantiating an engine/adding plugins are cheap operations that works as the solution as a new engine will have a fresh/clean context.

Thoughts @FlorianRappl?

**Comment by FlorianRappl** [comment]
All of the named operations should be quite cheap. The engine context is just a plain .NET dictionary (or anything that implements `IDictionary<String, Object>`). If you want to wipe that then using the `Clear` method would do the job. I don't think that a growing scope (dictionary) should do any performance hit (due to O(1) access), however, the increased memory consumption may become a problem. So cleaning up unneeded stuff would certainly be beneficial.

@wootencl does that already help you or should we have a more in-detail look?

**Comment by wootencl** [comment]
@FlorianRappl Think that perfectly answers my question. Mostly wasn't sure whether or not this line `engine.Interpret("test_func = (x, y) => x * y");` would store `test_func` in the engine scope or another data store (probably should have dug a little deeper into the source to answer my own question). As `test_func` seems to be wiped with a `engine.Scope.Clear()` it should work perfectly for my use case of "resetting" the engine.

Thanks for the help! Going to close this issue.
